kube-prometheus-stack:
  alertmanager:
    enabled: false

  defaultRules:
    create: false

  grafana:
    enabled: false

  kubeStateMetrics:
    enabled: false

  kubeApiServer:
    enabled: false

  kubelet:
    enabled: false

  kubeControllerManager:
    enabled: false

  coreDns:
    enabled: false

  kubeEtcd:
    enabled: false

  kubeScheduler:
    enabled: false

  kubeProxy:
    enabled: false

  nodeExporter:
    enabled: false

  prometheus:
    serviceMonitor:
      selfMonitor: false
    
  prometheusOperator:
    enabled: true
    serviceMonitor:
      selfMonitor: false

  serviceMonitor:
    enabled: false
  
grafana:
  admin:
    username: admin
    password: secret

kafkaNamespaces:
  - cf
