kube-prometheus-stack:
  defaultRules:
    create: false

  grafana:
    enabled: false

  alertmanager:
    enabled: false

  nodeExporter:
    enabled: false

  kubeStateMetrics:
    enabled: false

  prometheusOperator:
    enabled: true

  kubeApiServer:
    enabled: false

  kubelet:
    enabled: false

  kubeControllerManager:
    enabled: false

  coreDns:
    enabled: false

  kubeEtcd:
    enabled: false

  kubeScheduler:
    enabled: false

  kubeProxy:
    enabled: false

  serviceMonitor:
    enabled: false
  
grafana:
  admin:
    username: admin
    password: secret

kafkaNamespaces:
  - cf
  - rms
