kube-prometheus-stack:
  alertmanager:
    enabled: false

  defaultRules:
    create: false

  grafana:
    enabled: false

  kubeStateMetrics:
    enabled: false

  kubeApiServer:
    enabled: false

  kubelet:
    enabled: false

  kubeControllerManager:
    enabled: false

  coreDns:
    enabled: false

  kubeEtcd:
    enabled: false

  kubeScheduler:
    enabled: false

  kubeProxy:
    enabled: false

  nodeExporter:
    enabled: false

  prometheus:
    serviceMonitor:
      selfMonitor: false
    
  prometheusOperator:
    enabled: true
    serviceMonitor:
      selfMonitor: false

  serviceMonitor:
    enabled: false
  
grafana:
  ingress: false
  admin:
    username: admin
    password: secret

envSelectorLabel: "env"

cfkEnvs:
  - namespace: cf
    identifier: platformatory
    serviceType: kafka
      
ansibleEnvs:
  - name: sentinel
    labels:
      job: kafka
      env: sentinel
    targets:
      - 45.79.126.76:8080
