{{- range $ansibleEnv := .Values.ansibleEnvs }}
apiVersion: monitoring.coreos.com/v1alpha1
kind: ScrapeConfig
metadata:
  name: {{ $.Release.Name }}-cp-ansible-{{ $ansibleEnv.name }}
  labels:
{{- include "kube-prometheus-kafka.labels" $ | nindent 4 }}
    release: {{ $.Release.Name }}
spec:
  staticConfigs:
    - labels:
{{- range $key, $value := $ansibleEnv.labels }}
        {{ $key }}: {{ $value }}
{{- end }}    
    - targets:
{{- range $target := $ansibleEnv.targets }}
        - {{ $target }}
{{- end }}    
---    
{{- end }}
