{{- range $cfkEnv := .Values.cfkEnvs }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $.Release.Name }}-kafka-{{ $cfkEnv.namespace }}-{{ $cfkEnv.identifier }}
  labels:
{{- include "kube-prometheus-kafka.labels" $ | nindent 4 }}
    release: {{ $.Release.Name }}
spec:
  namespaceSelector:
    matchNames:
    - {{ $cfkEnv.namespace }}
  selector:
    matchLabels:
      {{ $.Values.envSelectorLabel }}: {{ $cfkEnv.identifier }}
      type : {{ $cfkEnv.serviceType }}
  endpoints:
  - path: /metrics
    targetPort: 7778
  targetLabels:
  - {{ $.Values.envSelectorLabel }}
  - type
---    
{{- end }}
