{{- range $namespace := .Values.kafkaNamespaces }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $.Release.Name }}-kafka-{{ $namespace }}
  labels:
{{- include "kube-prometheus-kafka.labels" $ | nindent 4 }}
    release: {{ $.Release.Name }}
spec:
  namespaceSelector:
    matchNames:
    - {{ $namespace }}
  selector:
    matchLabels:
      env: {{ $namespace }}
  endpoints:
  - path: /metrics
    targetPort: 7778
  targetLabels:
  - env
---    
{{- end }}
